name: LaravelTests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: testing_test_1
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Create test databases
        run: |
          mysql -hmysql -uroot -ppassword -e 'DROP DATABASE IF EXISTS testing_test_1; CREATE DATABASE testing_test_1;'
          mysql -hmysql -uroot -ppassword -e 'DROP DATABASE IF EXISTS testing_test_2; CREATE DATABASE testing_test_2;'
          mysql -hmysql -uroot -ppassword -e 'DROP DATABASE IF EXISTS testing_test_3; CREATE DATABASE testing_test_3;'
          mysql -hmysql -uroot -ppassword -e 'DROP DATABASE IF EXISTS testing_test_4; CREATE DATABASE testing_test_4;'
          mysql -hmysql -uroot -ppassword -e 'DROP DATABASE IF EXISTS testing_test_5; CREATE DATABASE testing_test_5;'

      - name: Prepare application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
        run: composer test
