name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    name: Laravel Paratest
    runs-on: ubuntu-latest

    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: testing_test_1
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-scripts"

      - name: Create test databases
        run: |
          mysql -hmysql -uroot -ppassword -e 'DROP DATABASE IF EXISTS testing_test_1; CREATE DATABASE testing_test_1;'
          mysql -hmysql -uroot -ppassword -e 'DROP DATABASE IF EXISTS testing_test_2; CREATE DATABASE testing_test_2;'
          mysql -hmysql -uroot -ppassword -e 'DROP DATABASE IF EXISTS testing_test_3; CREATE DATABASE testing_test_3;'
          mysql -hmysql -uroot -ppassword -e 'DROP DATABASE IF EXISTS testing_test_4; CREATE DATABASE testing_test_4;'

      - name: Prepare application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
        run: php artisan test --parallel --processes=4 --recreate-databases
        # run: ./vendor/bin/sail test
